using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Microsoft.EntityFrameworkCore.SqlServer.Test.Models.Migrations
{
    internal sealed class MigrationContext1 : MigrationContext<Patriarch>
    {
        private static readonly HierarchyId _rootHid = HierarchyId.GetRoot();
        private static readonly HierarchyId _childHid1 = HierarchyId.Parse("/1/");
        private static readonly HierarchyId _childHid2 = HierarchyId.Parse("/2/");

        protected override void SeedData(EntityTypeBuilder<Patriarch> builder)
        {
            builder.HasData(
                new Patriarch { Id = _rootHid, Name = "Eddard Stark" },
                new Patriarch { Id = _childHid1, Name = "Robb Stark" },
                new Patriarch { Id = _childHid2, Name = "Jon Snow" });
        }

        public override string GetExpectedMigrationCode(string migrationName, string @namespace)
        {
            return @"using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

namespace " + @namespace + @".Migrations
{
    public partial class " + migrationName + @" : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: ""TestModels"",
                columns: table => new
                {
                    Id = table.Column<HierarchyId>(nullable: false),
                    Name = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey(""PK_TestModels"", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: ""TestModels"",
                columns: new[] { ""Id"", ""Name"" },
                values: new object[] { Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/""), ""Eddard Stark"" });

            migrationBuilder.InsertData(
                table: ""TestModels"",
                columns: new[] { ""Id"", ""Name"" },
                values: new object[] { Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/1/""), ""Robb Stark"" });

            migrationBuilder.InsertData(
                table: ""TestModels"",
                columns: new[] { ""Id"", ""Name"" },
                values: new object[] { Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/2/""), ""Jon Snow"" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: ""TestModels"");
        }
    }
}
";
        }

        public override string GetExpectedSnapshotCode(string @namespace)
        {
            return @"// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.SqlServer.Test.Models.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace " + @namespace + @".Migrations
{
    [DbContext(typeof(" + nameof(MigrationContext1) + @"))]
    partial class " + nameof(MigrationContext1) + @"ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity(""Microsoft.EntityFrameworkCore.SqlServer.Test.Models.Patriarch"", b =>
                {
                    b.Property<HierarchyId>(""Id"")
                        .HasColumnType(""hierarchyid"");

                    b.Property<string>(""Name"")
                        .HasColumnType(""nvarchar(max)"");

                    b.HasKey(""Id"");

                    b.ToTable(""TestModels"");

                    b.HasData(
                        new
                        {
                            Id = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/""),
                            Name = ""Eddard Stark""
                        },
                        new
                        {
                            Id = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/1/""),
                            Name = ""Robb Stark""
                        },
                        new
                        {
                            Id = Microsoft.EntityFrameworkCore.HierarchyId.Parse(""/2/""),
                            Name = ""Jon Snow""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
";
        }
    }
}
